### ISSUE TITLE
Create symbolic links under /opt/rocm in the installer

### ISSUE THREAD

**Issue by bragadeesh** [ROCmSoftwarePlatform/rocRAND#11]
Symbolic links for  rocrand & hiprand libraries and headers are missing under /opt/rocm/lib  and /opt/rocm/include . Like other roc libraries such as rocBLAS, we need to create symbolic links for hiprand and rocrand under /opt/rocm during installation from the .deb package etc.

**Comment by jszuppe** [comment]
I thought `postinst`  install script is doing it.

**Comment by bragadeesh** [comment]
closing this for now
