### ISSUE TITLE
hip_hcc.so dependency issue when instaill *.rpm 

### ISSUE THREAD

**Issue by tingxingdong** [ROCmSoftwarePlatform/rocRAND#14]
Environment: CentOS 7,4 + gcc 7.4 + Vega10 + ROCM 1.7.x 

trying to install rocrand *.rpm, with the libhip_hcc.so()(64bit) dependency unresolved. 
No such issue on rocFFT which does not depend on libhip_hcc.so but hip_hcc >= 1.3.

Is hip_hcc.so a CUDA compatible library?   see here
_" I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally"_ in https://github.com/ROCmSoftwarePlatform/hiptensorflow/issues/28

=================================
[root@af5c7d5e5ccb build]# yum install rocrand-1.7.1-1.x86_64.rpm
Loaded plugins: fastestmirror, ovl
Examining rocrand-1.7.1-Linux.rpm: rocrand-1.7.1-1.x86_64
Marking rocrand-1.7.1-Linux.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package rocrand.x86_64 0:1.7.1-1 will be installed
--> Processing Dependency: libhip_hcc.so()(64bit) for package: rocrand-1.7.1-1.x86_64
Loading mirror speeds from cached hostfile
 * base: pubmirrors.dal.corespace.com
 * epel: mirror.compevo.com
 * extras: centos.mirror.lstn.net
 * updates: mirror.hackingand.coffee
--> Finished Dependency Resolution
**_Error: Package: rocrand-1.7.1-1.x86_64 (/rocrand-1.7.1-Linux)
           Requires: libhip_hcc.so()(64bit)_**
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

=================================

[root@af5c7d5e5ccb build]# yum deplist  rocrand-1.7.1-1.x86_64.rpm
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: pubmirrors.dal.corespace.com
 * epel: mirror.compevo.com
 * extras: centos.mirror.lstn.net
 * updates: mirror.hackingand.coffee
package: rocrand.x86_64 1.7.1-1
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-29.el7_4
  dependency: libc.so.6()(64bit)
   provider: glibc.x86_64 2.17-196.el7_4.2
  dependency: libc.so.6(GLIBC_2.14)(64bit)
   provider: glibc.x86_64 2.17-196.el7_4.2
  dependency: libc.so.6(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.17-196.el7_4.2
  dependency: libc.so.6(GLIBC_2.4)(64bit)
   provider: glibc.x86_64 2.17-196.el7_4.2
  dependency: libdl.so.2()(64bit)
   provider: glibc.x86_64 2.17-196.el7_4.2
  dependency: libdl.so.2(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.17-196.el7_4.2
  dependency: libgcc_s.so.1()(64bit)
   provider: libgcc.x86_64 4.8.5-16.el7_4.2
  dependency: libgcc_s.so.1(GCC_3.0)(64bit)
   provider: libgcc.x86_64 4.8.5-16.el7_4.2
  dependency: libhc_am.so()(64bit)
   provider: hcc.x86_64 1.2.18054-1
  _**dependency: libhip_hcc.so()(64bit)
   Unsatisfied dependency**_

[root@af5c7d5e5ccb rocFFT_BUILD_TOOLSET7]# yum deplist rocfft-0.8.1.0-Linux.rpm
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: pubmirrors.dal.corespace.com
 * epel: mirror.compevo.com
 * extras: centos.mirror.lstn.net
 * updates: mirror.hackingand.coffee
package: rocfft.x86_64 0.8.1.0-1
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-29.el7_4
  **_**dependency: hip_hcc >= 1.3
   provider: hip_hcc.x86_64 1.5.18092-1**_**

**Comment by bragadeesh** [comment]
@jszuppe 
We are working on centos support. After generating rocrand RPM , it errors out during installation
can you help with this?

**Comment by jszuppe** [comment]
Sure, I can look into it. I don't have a docker image with CentOS and ROCm right now, but I'll try. 

>No such issue on rocFFT which does not depend on this *.so.

That's odd. rocFFT also links against that lib: https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/library/src/CMakeLists.txt#L58 It's a basic HIP/HCC lib.

**Comment by bragadeesh** [comment]
what Tim means is that the package name differs, in rocfft case it is hip_hcc, whereas rocrand seem to depend on the so name specifically

**Comment by jszuppe** [comment]
Try adding

```cmake
set(CPACK_RPM_PACKAGE_RELOCATABLE OFF)
set( CPACK_RPM_PACKAGE_AUTOREQPROV OFF CACHE BOOL "" )
```

before line https://github.com/ROCmSoftwarePlatform/rocRAND/blob/develop/library/CMakeLists.txt#L250

**Comment by tingxingdong** [comment]
Hi, @jszuppe Thanks, the 2 lines work!
can you explain why a little bit?

**Comment by jszuppe** [comment]
`CPACK_RPM_PACKAGE_RELOCATABLE` is not related, but it's better to turn it off since we don't need a relocatable package. As for `CPACK_RPM_PACKAGE_AUTOREQPROV` CPack option, turning it off disables automatic detection of shared libraries dependencies. After Braga commented that it depends on the so name specifically, I remembered that this option is turned off in rocm-cmake and what the option does.

**Comment by bragadeesh** [comment]
Thanks @jszuppe

**Comment by jszuppe** [comment]
I'm glad I could help.
