### ISSUE TITLE
Invalid use of inline assembly for GFX1010 target

### ISSUE THREAD

**Issue by rigtorp** [ROCmSoftwarePlatform/rocRAND#140]
**Describe the bug**

When building PyTorch the following error is observed:
```
[ 86%] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THHUNN/torch_hip_generated_RReLU.hip.o
<inline asm>:1:24: error: invalid operand for instruction
        v_mad_u64_u32 v[2:3], s[10:11], s1, v42, v[8:9]
                              ^
note: !srcloc = 13700931
<inline asm>:1:24: error: invalid operand for instruction
        v_mad_u64_u32 v[4:5], s[10:11], s46, v42, v[8:9]
```

I traced this down to use of inline assembly in rocRAND:
```
/opt/rocm-3.7.0/rocrand/include/rocrand_common.h
61:    asm volatile("v_mad_u64_u32 %0, %1, %2, %3, %4"
```

If I comment out the above line, the PyTorch build proceeds.

**To Reproduce**
Build PyTorch with ROCm, see ROCmSoftwarePlatform/pytorch#718

**Expected behavior**
Build succeeds.

**Comment by doctorcolinsmith** [comment]
@rigtorp Thanks for reporting the issue.  We're working to fix the invalid use of v_mad_u64_u32 on gfx10 series hardware in an upcoming release.  You may see this same error recur in other ROCm libraries.

**Comment by saadrahim** [comment]
A fix has been merged into the develop branch. @rigtorp Please verify if this resolves your issue. I will assume the issue is resolved in a week and close the ticket if no response is received.

**Comment by rigtorp** [comment]
Yes PyTorch builds for GFX1010 now. But I cannot confirm functionality until https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/180 has been fixed.

**Comment by saadrahim** [comment]
Work on that issue is ongoing.
