### ISSUE TITLE
Can the rocRAND v1.7.1 run on Carrizo?

### ISSUE THREAD

**Issue by QWU-AMD** [ROCmSoftwarePlatform/rocRAND#17]
Hello,

I can build the rocRAND v1.7.1 on my Carrizo machine. However, if I run the
**./benchmark_rocrand_generate --engine all --dis all**

it will crash:
**xorwow:
  uniform-uint:
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _ZN12rocrand_host6detail19init_engines_kernelEPN14rocrand_device13xorwow_engineEyy
Aborted (core dumped)**

My system info is:
Ubuntu 16.04.4 LTS
rocm-dkms   1.7.137
HIP version  : 1.5.0
GPU: Carrizo

If I run the same built executable on Vega machine, there's no crash.

Thanks,
Qiyu

**Comment by jszuppe** [comment]
That looks like some problem with ROCm not with rocRAND. Unless other roc*/hip* libraries work on your Carrizo machine, do they?

**Comment by jszuppe** [comment]
Does `rocminfo` detect Carrizo and print information about it?

**Comment by QWU-AMD** [comment]
Thanks for the reply. I run the rocminfo, it detects the gfx801 (which is Carrizo) and print the information about it.

**Comment by jszuppe** [comment]
Sorry, I've read the error incorrectly. Solution: add `gfx801` to AMD_TARGETS cmake option (https://github.com/ROCmSoftwarePlatform/rocRAND/blob/master/CMakeLists.txt#L56), so `-DAMD_TARGETS=gfx801` when you're running cmake.

**Comment by jszuppe** [comment]
Please close if that solves your problem.

**Comment by QWU-AMD** [comment]
I added the -DAMD_TARGETS=gfx801 when running cmake. I still get the same error message.

**Comment by jszuppe** [comment]
`AMDGPU_TARGETS`

**Comment by QWU-AMD** [comment]
It works! Thanks!
