### ISSUE TITLE
rocRand is compiled without gfx803 support

### ISSUE THREAD

**Issue by gBaltar** [ROCmSoftwarePlatform/rocRAND#177]
Loading of pytorch failed because of missing code object for gfx803. All other rocm libs are fine, just this one failed. Works with local build.

Version:
**rocrand4.2.0_2.10.9.40200-21_amd64.deb**

Error:
:1:hip_code_object.cpp      :456 : 15814696557 us: hipErrorNoBinaryForGpu: Unable to find code object for all current devices!
:1:hip_code_object.cpp      :458 : 15814696572 us:   Devices:
:1:hip_code_object.cpp      :460 : 15814696575 us:     amdgcn-amd-amdhsa--gfx803 - [Not Found]
:1:hip_code_object.cpp      :465 : 15814696578 us:   Bundled Code Objects:
:1:hip_code_object.cpp      :482 : 15814696581 us:     host-x86_64-unknown-linux - [Unsupported]
:1:hip_code_object.cpp      :479 : 15814696585 us:     hipv4-amdgcn-amd-amdhsa--gfx900:xnack- - [code object v4 is amdgcn-amd-amdhsa--gfx900:xnack-]
:1:hip_code_object.cpp      :479 : 15814696589 us:     hipv4-amdgcn-amd-amdhsa--gfx906:xnack- - [code object v4 is amdgcn-amd-amdhsa--gfx906:xnack-]
:1:hip_code_object.cpp      :479 : 15814696592 us:     hipv4-amdgcn-amd-amdhsa--gfx908:xnack- - [code object v4 is amdgcn-amd-amdhsa--gfx908:xnack-]
HIP/rocclr/hip_code_object.cpp:486: "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

**Comment by xuhuisheng** [comment]
Please refer here:
<https://github.com/xuhuisheng/rocm-build/tree/master/gfx803#rocm-41-and-rocm-42-crashed-with-gfx803>

**Comment by neon60** [comment]
Hi @gBaltar 

The following commit will be only available at 4.3:
https://github.com/ROCmSoftwarePlatform/rocRAND/commit/467824da5d312315dc97bf3590a1dd95ca0c6c55

The rocRAND library will support gfx803 after 4.3, until it can.

**Comment by neon60** [comment]
> Please refer here:
> https://github.com/xuhuisheng/rocm-build/tree/master/gfx803#rocm-41-and-rocm-42-crashed-with-gfx803
> 
> ROCm-4.3 will fix this issue #170

You were faster.

**Comment by gBaltar** [comment]
Thanks
