### ISSUE TITLE
Issue installing rocRAND (HIP version  : 1.5.18205)

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/rocRAND#19]
Hi! It appears that when building rocRAND, it does not include the path /opt/rocm/hcc/include/ as a library search path (-L/opt/rocm/hcc/include/), leading to the error below.

/opt/rocm/hip/include/hip/hcc_detail/hip_runtime.h:61:10: fatal error: 'grid_launch.h' file not found
#include <grid_launch.h>

**Comment by ex-rzr** [comment]
Could you show output of `hipconfig`?

**Comment by ex-rzr** [comment]
Is this the first time you observe this issue? What about older versions of HIP and HCC?

I'm asking because we have 1.5.18151 and 1.5.18081, everything is ok.
