### ISSUE TITLE
Use mtgp32_kernel_params field inside of mtgp_engine for better OO design.

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/rocRAND#22]
I don't see why you're diverging from CUDA for no good reason. I noticed a redundancy with the design of the mtgp_engine class.

**This is how it's already done in CUDA.**
```
struct curandStateMtgp32 {
    unsigned int s[MTGP32_STATE_SIZE];
    int offset;
    int pIdx;
    mtgp32_kernel_params_t * k;
    int precise_double_flag;
};
```
**Let's take a look at rocRAND.**
Fields of the [mtgp32_kernel_params_t class](https://github.com/ROCmSoftwarePlatform/rocRAND/blob/1890bb31675a6cbaa7766e947c8e35c4d1010ad6/library/include/rocrand_mtgp32.h#L320):
```
public:
    // State
    mtgp32_state m_state;
    // Parameters
    unsigned int pos_tbl;
    unsigned int param_tbl[MTGP_TS];
    unsigned int temper_tbl[MTGP_TS];
    unsigned int single_temper_tbl[MTGP_TS];
    unsigned int sh1_tbl;
    unsigned int sh2_tbl;
    unsigned int mask;
```

Fields of t [mtgp32_kernel_params_t](https://github.com/ROCmSoftwarePlatform/rocRAND/blob/1890bb31675a6cbaa7766e947c8e35c4d1010ad6/library/include/rocrand_mtgp32.h#L113):
```
    unsigned int pos_tbl[MTGP_BN_MAX];
    unsigned int param_tbl[MTGP_BN_MAX][MTGP_TS];
    unsigned int temper_tbl[MTGP_BN_MAX][MTGP_TS];
    unsigned int single_temper_tbl[MTGP_BN_MAX][MTGP_TS];
    unsigned int sh1_tbl[MTGP_BN_MAX];
    unsigned int sh2_tbl[MTGP_BN_MAX];
    unsigned int mask[1];

```

Why not simply define the **mtgp_engine** class to have a pointer to **mtgp32_kernel_params_t**?

**Example:**
```
public:
    // State
    mtgp32_state m_state;
    // Parameters
    mtgp32_kernel_params_t * k;
```

**Reason One**
Better object oriented design. I should be able to create a single mtgp32_kernel_params and reuse that object in other hiprandStateMtgp32_t states. Otherwise, you'll have to do bloated things such as 

```
my_state.pos_tbl = mtgp32_kernel_params.pos_tbl;
my_state.param_tbl = mtgp32_kernel_params.param_tbl;
my_state.temper_tbl = mtgp32_kernel_params.temper_tbl;
my_state.single_temper_tbl = mtgp32_kernel_params.single_temper_tbl;
my_state.sh1_tbl = mtgp32_kernel_params.sh1_tbl;
my_state.sh2_tbl = mtgp32_kernel_params.sh2_tbl;
my_state.mask = mtgp32_kernel_params.mask;
```

**Reason Two**
Unnecessary divergence from the CUDA API leading to more work to have new frameworks run seamlessly.

**Comment by ex-rzr** [comment]
@Jorghi12 But why exactly do these new frameworks need access to "private" types? (by "private" I mean anything that is not listed in https://docs.nvidia.com/cuda/curand/group__HOST.html and https://docs.nvidia.com/cuda/curand/group__DEVICE.html).

**Comment by Jorghi12** [comment]
Here's an example with CUDA: https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCTensorRandom.cu#L64

The field isn't private in CUDA. 

For example, notice how the curandMakeMTGP32KernelState method takes in a mtgp32_kernel_params_t argument.

`__host__ ​ curandStatus_t CURANDAPI curandMakeMTGP32KernelState ( curandStateMtgp32_t* s, mtgp32_params_fast_t params[], mtgp32_kernel_params_t* k, int  n, unsigned long long seed )`

**Comment by ex-rzr** [comment]
That's exactly what I'm asking about: both host and device cuRAND APIs work with `*_t` types, i.e. there is `mtgp32_kernel_params_t` but no `mtgp32_kernel_params`.

What does pyTorch uses such types? Does it implement something that is not possible to accomplish using public APIs?

**Comment by Jorghi12** [comment]
I just didn't see any reason for the divergence away from the CUDA API and wondered why such decisions were made. This isn't urgent but it'd be nice to have.

**Comment by Jorghi12** [comment]
@ex-rzr I think my original proposal may not be coming across clearly enough.

I don't want a mtgp32_kernel_params exposed at all. 

I'm simply saying that the mtgp_engine class should have a pointer to a mtgp32_kernel_params_t object.

**Comment by jszuppe** [comment]
`mtgp32_kernel_params_t` is not private, but its fields are implementation details. The same goes for fields of `curandState<>` structures.

> Here's an example with PyTorch & CUDA: https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCTensorRandom.cu#L64

The fact that it's used in PyTorch does not mean it's correct usage.

**Comment by Jorghi12** [comment]
@jszuppe @ex-rzr Ignore the example I linked you to. That's a totally separate ordeal. Please re-read the initial message.

**Comment by Jorghi12** [comment]
@jszuppe I believe we're discussing different things. From _within device code_, surely it would still be a nice to have to be able to pass mtgp32_kernel_params_t objects around to different mtgp_engine classes instead.

**Comment by jszuppe** [comment]
> Please re-read the initial message.

Yeah. We get that. We don't remember exactly why it was done that way. It might have to do something with performance, or just missed (it happens; that was not  the most important part of the project and it's not like the time was unlimited). `mtgp32_kernel_params_t` is not the same as fields in `mtgp_engine`, because it's bigger. I get that pointer may solve that, and that's a valid idea. We would need to check performance. We will look at this when we have time.

>  I believe we're discussing different things.

Maybe. We're just saying: what's not in a public API is an implementation detail, and I think that's obvious.

**Comment by Jorghi12** [comment]
I'd recommend seeing page 30 of http://www.math.univ-paris13.fr/~cuvelier/docs/Informatique/CUDA/docs/5.0/CURAND_Library.pdf

**Comment by jszuppe** [comment]
> Sounds great. Yes I agree, it's not part of the public API, but it would be nice to maintain the idiosyncrasies.

> I wouldn't have expected this to be caught at all given how subtle it is and how unrelated it is to the actual public API.

Yeah. We can't predict what implementation details or implementation defined behaviours  (like in [here](https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCTensorRandom.cu#L64)) will be used by developers that uses cuRAND. We can just hope that developers are sane ;) and it won't happen often. We will consider you request and check how it affects performance.

> The rocRAND API works very well as a whole and has improved on many different levels from the hcRNG package.

Let's not talk about hcRNG :D

**Comment by Jorghi12** [comment]
@jszuppe Haha oh the horror of hcRNG xD

**Comment by jszuppe** [comment]
I'm not sure if we will do that change as using pointer significantly decreases performance of MTGP32 RNG. The drops are: from 180GB/s to 102GB/s on my GTX1080, and from 263GB/s to 156 GB/s on MI25.

**Comment by Jorghi12** [comment]
@jszuppe Yeah, adding a function for that is just fine.

**Comment by jszuppe** [comment]
@Jorghi12 check https://github.com/ROCmSoftwarePlatform/rocRAND/commit/23a729494914db922687ea7e0718451751f1fd56

**Comment by jszuppe** [comment]
@Jorghi12 Have you checked 23a7294? Can I close this issue?

**Comment by jszuppe** [comment]
I'm closing this. Please reopen if you still have some issues.
