### ISSUE TITLE
Request: Better handling of sign when doing comparisons.

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/rocRAND#24]
While running though rocRAND I saw a comparison between **unsigned** and **signed** integers. An example shown here where **variable i is signed** but **variable v is unsigned**.
https://github.com/ROCmSoftwarePlatform/rocRAND/blob/master/library/include/rocrand_xorwow.h#L220

I'd prefer to have equivalency between types throughout the codebase. The difference between signed and unsigned integers is that the last bit is interpreted differently.

While this isn't a major issue at the moment, it'd be nice to have it handled in the future.

**Comment by Jorghi12** [comment]
This might not be that big of an issue. I only saw it on that single line I pointed out.

**Comment by jszuppe** [comment]
Yeah, that `i` will be very small IIRC and always positive, so there is not problem in that line. `i` will be converted to `unsigned long long` (C++ behaviour) and compared.

**Comment by Jorghi12** [comment]
@jszuppe Yeah, I didn't expect that this case would have an issue. But simply wanted to point it out.

Unnecessary remark removed.

**Comment by jszuppe** [comment]
Fixed.
