### ISSUE TITLE
Test 4 hangs

### ISSUE THREAD

**Issue by dcolley** [ROCmSoftwarePlatform/rocRAND#26]
* ubuntu 16.04
* cmake 3.9.4
* hcc 7.0.0

I cloned the rocRAND repo, and tried to build is as per instructions. 
For some reason it was trying to include CUDA. E.g. various options in library/CMakeLists.txt [lines 35 and 50]

So I used:
`CXX=/opt/rocm/bin/hcc cmake -DBUILD_BENCHMARK=ON -DHIP_PLATFORM=hcc ../.`

Then I tried the tests:
```~/project/rocRAND/build$ ctest --output-on-failure
Test project /home/derek/project/rocRAND/build
      Start  1: test_log_normal_distribution
 1/26 Test  #1: test_log_normal_distribution ........   Passed    0.05 sec
      Start  2: test_normal_distribution
 2/26 Test  #2: test_normal_distribution ............   Passed    0.05 sec
      Start  3: test_poisson_distribution
 3/26 Test  #3: test_poisson_distribution ...........   Passed    6.29 sec
      Start  4: test_rocrand_basic
```
... and it never returns.

**Comment by jszuppe** [comment]
If you can please post output from `hipconfig` and tell us what GPU you have. 

>I cloned the rocRAND repo, and tried to build is as per instructions.
For some reason it was trying to include CUDA. E.g. various options in library/CMakeLists.txt [lines 35 and 50]

Do you have CUDA installed too, and is your ROCm platform installed correctly? I'm asking because it seems that HIP cmake script (loaded by `find_package(HIP REQUIRED)`) sets `HIP_PLATFORM` to `nvcc`, not `hcc`. Incorrect ROCm installation might also be the reason why `test_rocrand_basic` fails. The first 3 tests that pass are pure C++ tests and don't use ROCm libraries, that's why they don't hang.

**Comment by dcolley** [comment]
I have no Nvidia cards, so I didn't install CUDA - and I prefer not to...
My goal is to run tensorflow on AMD GPUs - I have multiple RX580

```
/opt/rocm/hip/bin/hipconfig
HIP version  : 1.5.18151

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/include -I/usr/local/cuda/include

== nvcc
Can't exec "nvcc": No such file or directory at /opt/rocm/hip/bin/hipconfig line 143.

=== Environment Variables
PATH=/home/derek/bin:/home/derek/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/computecpp/bin:/usr/local/computecpp/bin
LD_LIBRARY_PATH=/usr/local/computecpp/lib:/home/derek/.local/lib/python3.5/site-packages/external/local_config_rocm/rocm/rocm/lib

== Linux Kernel
Hostname     : host2
Linux host2 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by jszuppe** [comment]
See, hipconfig does not detect ROCm platform. Are you able to compile any HIP/OpenCL code and run in on AMD GPU (ROCM platform)?

**Comment by dcolley** [comment]
I'm out of my depth here :/ (c++ is not my thing, and I am actually after tensorflow, not HIP/OpenCL [yet])

I started with this post https://gpuopen.com/rocm-tensorflow-1-8-release
It points to https://rocm.github.io/ROCmInstall.html 

`sudo apt install rocm-dkms` conflicted with amd-dkms, so I had to frig apt to force the installation. 
However:
```
/opt/rocm/bin/rocminfo
hsa api call failure at line 900, file: /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.8/rocminfo/rocminfo.cc. Call returned 4104
```
I will go back to a fresh installation and run the process again... will update you with my findings.

**Comment by dcolley** [comment]
Just for info: I did the Hello World tutorial - about 2 weeks ago, and I was able to run the code on GPU

**Comment by dcolley** [comment]
Ok, I now see that was from https://developer.codeplay.com/computecppce/latest/sycl-guide-hello-sycl - probably not the same thing as hip.

It still runs:
```
~/sycl/hello/build$ ./hello
Running on Ellesmere
Hello, World!
  A { 1, 2, 3, 4 }
+ B { 4, 3, 2, 1 }
------------------
= C { 5, 5, 5, 5 }
```
While trying to get TF working on AMD GPU, I've had an *indirect* journey so far... 
ComputeCpp's version of TF is currently 1.3 - it worked for me, but on some cases 1.3 was not sufficient
The announcement of 1.8 above sent me down this rabbit hole ;)

**Comment by sunway513** [comment]
Hi @dcolley, it's optional to build rocRAND or the other libraries from source, if your eventual goal is to enable TF1.8 on AMD GPUs. 
Please follow the steps below and create an issue on the TF repo if you have questions:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md

**Comment by dcolley** [comment]
@sunway513 @jszuppe thank you both for you patience. It's clear that rocRAND is not the cause of the underlying problem. 
I followed the instructions on the link, and TF models/tutorials/image/imagenet/classify_image.py is segfaulting...
```
$ python3 classify_image.py 
>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
2018-08-04 21:07:23.600151: W tensorflow/core/framework/op_def_util.cc:346] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2018-08-04 21:07:23.701229: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
terminate called after throwing an instance of 'ihipException'
  what():  std::exception
Aborted (core dumped)
```
I'll move over to tensorflow-upstream to see if someone can help there
:thumbsup:
