### ISSUE TITLE
rocrand-config.cmake directory

### ISSUE THREAD

**Issue by ntrost57** [ROCmSoftwarePlatform/rocRAND#38]
rocrand is (as far as I know) the only library that installs its `rocrand-config.cmake` and related files in `<rocm-dir>/lib/cmake/rocrand/rocrand/`
All other libraries install to `<rocm-dir>/lib/cmake/<roclib>/`
Is there a special reason for that?

**Comment by ex-rzr** [comment]
This is very strange.
How do you build and install rocRAND?

I've just checked three ways:
1. `sudo make install`
2. `make package`, then `sudo dpkg -i rocrand-1.8.2-Linux.deb `
3. `sudo apt install rocrand`

All commands create `/opt/rocm/rocrand/lib/cmake/rocrand/rocrand-config.cmake` and `/opt/rocm/rocrand/include/rocrand.h`, i.e. without this strange `rocrand/rocrand` path.

**Comment by ntrost57** [comment]
It is about `/opt/rocm/lib/cmake/` where all symlinks are created. Here, the directory is wrong.

**Comment by ex-rzr** [comment]
Fixed in #58
