### ISSUE TITLE
StackGuardSlot compile errors independent of hcc version

### ISSUE THREAD

**Issue by chazanov** [ROCmSoftwarePlatform/rocRAND#49]
Several people have reported (https://github.com/ROCmSoftwarePlatform/rocRAND/issues/40 https://github.com/ROCmSoftwarePlatform/rocRAND/issues/41 https://github.com/RadeonOpenCompute/hcc/issues/999 )
that rocRAND does not compile under ArchLinux. This error occurred for @baerbock , @Palmitoxico , ArchLinux packager Okoński and me. We have used different versions of hip+hcc (2.0 / 2.1 and master) for multiple times, but all failed with the same error.

I'm using latest hcc & hip (`HCC clang version 9.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 2d7f3a3c8f385c0aba115a6eed3ca96dd0b289e9) (https://github.com/RadeonOpenCompute/llvm.git 5f38a9683361416cfecc3e9c55f8c48dc5d5a041) (based on HCC 1.3.19064-46916709-2d7f3a3c8f-5f38a968336 )`
`HIP version: 1.5.19064`), which @ex-rzr confirms as working, but it won't compile.

There must be a cause for this OUTSIDE of hip & hcc/clang.

**Comment by ex-rzr** [comment]
@chazanov I'll try to build hcc+HIP+rocRAND on my Arch (hopefully today or this weekend).

**Comment by ex-rzr** [comment]
Hmm... I've managed to build rocRAND on my Arch: the library, all tests and benchmarks. No errors at all. I can't check on my computer, but these binaries work on one of our test servers with Ubuntu.

All ROCm packages are from AUR:
```
hcc
hip
rocm-cmake-git
rocr-runtime
roct-thunk-interface
```
As usual, `makepkg` except for HIP, where I manually set hcc platform with `HIP_PLATFORM=hcc makepkg` (because I have CUDA installed and AMD device not supported by ROCm).

For the future: probably the `hip` package should be divided in two packages: `hip-nvcc` and `hip-hcc` (just like official ROCm packages for Ubuntu).

(BTW, thank you all guys for maintaining Arch packages)

`HIP_PLATFORM=hcc /opt/rocm/hip/bin/hipconfig` reports this:
```
HIP version  : 1.5.19045

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/hip/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 8.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 683c680a6bff215baa3bd9d3099ba1a43e24cf2e) (https://github.com/RadeonOpenCompute/llvm.git 6e349ce344586b4254654aea8f34444a13aedb67) (based on HCC 1.3.19045-fea3e2b4-683c680a6b-6e349ce3445 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
LLVM (http://llvm.org/):
  LLVM version 8.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
HIP_PLATFORM=hcc

== Linux Kernel
Hostname     : ex
Linux extreality 4.19.20-1-lts #1 SMP Wed Feb 6 21:46:51 CET 2019 x86_64 GNU/Linux
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

rocRAND:
```
CXX=/opt/rocm/hcc/bin/hcc cmake -DBUILD_BENCHMARK=ON -DBUILD_CRUSH_TEST=ON -DDEPENDENCIES_FORCE_DOWNLOAD=ON -DHIP_PLATFORM=hcc ..
```

Perhaps there is a bug in hcc/clang/llvm triggered only in some conditions?
What differences do we have?
1. ROCm packages built in Release using `gcc (GCC) 8.2.1 20181127`.
2. My CPU is Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (IvyBridge).
3. What else?

If you want I can give you all my packages.

**Comment by chazanov** [comment]
@ex-rzr You are really helpful, thanks a lot! I think currently I don't need your packages.

J. Okonski has just packaged rocrand for Arch: https://aur.archlinux.org/packages/rocrand
Interestingly he also had to disable stack protection.

With working rocRAND I now have all the dependencies for TensorFlow. The build still fails, but this may be related to https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/280

Could you please also try to build TensorFlow with the Arch dependencies?

**Comment by ex-rzr** [comment]
Ok, this explains why I didn't see this issue: my `makepkg.conf` does not add `-fstack-protector-strong` to `CXXFLAGS`. When I manually add this option, I see the same crash.

(I'll check your TF build scripts)

**Comment by baerbock** [comment]
Just seeing this thread.
@ex-rzr Do you have a working TensorFlow binary for ArchLinux?

**Comment by ex-rzr** [comment]
@baerbock No, I couldn't build rocBLAS because its dependency Tensile does not support building without GPU: https://github.com/ROCmSoftwarePlatform/Tensile/issues/482
(As I mentioned I don't have ROCm supported GPU on my computer with Arch)

**Comment by saadrahim** [comment]
Hi,
If anyone can provide reproduction instructions for this issue on Ubuntu 16/18 or RHEL/Centos 7, I can request the compilers team provide a solution.

**Comment by ex-rzr** [comment]
@saadrahim 

```
CXXFLAGS=-fstack-protector-strong CXX=hcc cmake ..
make
```

**Comment by saadrahim** [comment]
> @saadrahim
> CXXFLAGS=-fstack-protector-strong CXX=hcc cmake ..
> make

Just to clarify, do we want to be able to compile with the FLAG set or do we need to be able to disable the  FLAG via CMake.

**Comment by baerbock** [comment]
@saadrahim _fstack-protector-strong_ currently has [to be disabled](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocrand), so please fix the compiler to ALLOW THE FLAG.

**Comment by saadrahim** [comment]
https://github.com/RadeonOpenCompute/ROCm#deprecation-notice---hcc
The hcc compiler is deprecated now. We are transitioning to the hipcc compiler. This issue is best revisited in again in the next few months.
