### ISSUE TITLE
rocRAND build issue with rocm-dev

### ISSUE THREAD

**Issue by QWU-AMD** [ROCmSoftwarePlatform/rocRAND#5]
Hi,

When I try to build rocRAND on AMD platform with rocm-dev (v1.6) installed, instead of rocm, there is error reported:
**command:**
cmake -DBUILD_BENCHMARK=ON ../.

**error:** 
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  cmake/NVCC.cmake:54 (find_package)
  cmake/Dependencies.cmake:12 (include)
  CMakeLists.txt:44 (include)

Do I have to have rocm instead of rocm-dev to build the rocRAND? 

Thanks,
Qiyu

**Comment by QWU-AMD** [comment]
HIP version  : 1.4.0

== hipconfig
HIP_PATH     : /opt/rocm/hip/bin
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/bin/include -I/usr/loc                                                                                                             al/cuda/include

== nvcc
Can't exec "nvcc": No such file or directory at ./hipconfig line 143.

=== Environment Variables
PATH=/opt/p4v/bin:/home/jenkins/bin:/home/jenkins/.local/bin:/usr/local/sbin:/us                                                                                                             r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by jszuppe** [comment]
That's the problem. `hipconfig` , and thus `FindHIP.cmake` module from `hip` which is used in rocRAND, sees your environment as a CUDA platform, not ROCm platform. Moreover, it can't find `nvcc` compiler. That's no a bug in rocRAND.

You should either add `nvcc` to your path and make sure CUDA is correctly installed, so `hipconfig` can find it, or make `hipconfig` see your environment as ROCm platform (I'm not sure how to do it if you have both CUDA and ROCm).

**Comment by whchung** [comment]
@QWU-AMD since you installed `rocm-dev` on your system, it appears you want to use ROCm stack.  you may want to check if your system has ROCm stack properly installed going to `/opt/rocm/hsa/sample`, and `make; ./vector_copy`, and check if the output is showing a kernel is properly executed.

you may also want to check https://rocm.github.io/hardware.html to verify if you are using ROCm-compatible hardware.

**Comment by QWU-AMD** [comment]
Thank you for replying! With rocm installed, things work fine.
