### ISSUE TITLE
Build error : no member named 'data' in 'uint4'

### ISSUE THREAD

**Issue by holyprince** [ROCmSoftwarePlatform/rocRAND#50]
When I try to build the rocRAND with the command:

cmake -DBUILD_BENCHMARK=OFF -DBUILD_TEST=OFF .. 

and the summary is :

-- ******** Summary ********
-- General:
--   System                : Linux
--   HIP ROOT              : /opt/rocm/hip
--   C++ compiler          : /opt/rocm/bin/hcc
--   C++ compiler version  : 7.0.0
--   CXX flags             : -Wno-unused-command-line-argument -Wall -Wextra
--   Build type            : Release
--   Install prefix        : /opt/rocm
--
--   BUILD_SHARED_LIBS     : ON
--   BUILD_FORTRAN_WRAPPER : OFF
--   BUILD_TEST            : OFF
--   BUILD_BENCHMARK       : OFF

I meet the problem : 

[ 70%] Building CXX object library/CMakeFiles/rocrand.dir/src/rocrand.cpp.o
In file included from /work/home/wangzh/rocRAND/library/src/rocrand.cpp:23:
In file included from /work/home/wangzh/rocRAND/library/src/rng/generators.hpp:24:
In file included from /work/home/wangzh/rocRAND/library/src/rng/philox4x32_10.hpp:62:
In file included from /work/home/wangzh/rocRAND/library/src/rng/device_engines.hpp:32:
In file included from /work/home/wangzh/rocRAND/library/include/rocrand_kernel.h:29:
/work/home/wangzh/rocRAND/library/include/rocrand_philox4x32_10.h:199:47: error: no member named 'data' in 'uint4'
            unsigned int ret = m_state.result.data[m_state.substate];

Must I open the BENCHMARK and TEST? because I cannot connect to the Internet, so I close it.

**Comment by VincentSC** [comment]
Could you provide the full log-file? I'm suspecting it did not correctly download dependencies, but cmake continued anyway. We wrote the cmake config assuming that there was internet available, so you could maybe build on another machine and transport the binaries?

**Comment by holyprince** [comment]
Thank you for your reply. This machine that I try to build cannot connect internet, so I turn off the build choice of BENCHMARK and TEST. Maybe the offline is the problem, or the whole library must turn on the  BENCHMARK  or TEST?
And the following is the full log-file:

[ build]$ make
[ 20%] Built target mrg32k3a_precomputed_generator
[ 40%] Built target xorwow_precomputed_generator
[ 60%] Built target sobol_direction_vector_generator
[ 70%] Building CXX object library/CMakeFiles/rocrand.dir/src/rocrand.cpp.o
In file included from /work/home/wangzh/rocRAND/library/src/rocrand.cpp:23:
In file included from /work/home/wangzh/rocRAND/library/src/rng/generators.hpp:24:
In file included from /work/home/wangzh/rocRAND/library/src/rng/philox4x32_10.hpp:62:
In file included from /work/home/wangzh/rocRAND/library/src/rng/device_engines.hpp:32:
In file included from /work/home/wangzh/rocRAND/library/include/rocrand_kernel.h:29:
/work/home/wangzh/rocRAND/library/include/rocrand_philox4x32_10.h:199:47: error: no member named 'data' in 'uint4'
            unsigned int ret = m_state.result.data[m_state.substate];
                               ~~~~~~~~~~~~~~ ^
1 error generated.
In file included from /work/home/wangzh/rocRAND/library/src/rocrand.cpp:23:
In file included from /work/home/wangzh/rocRAND/library/src/rng/generators.hpp:24:
In file included from /work/home/wangzh/rocRAND/library/src/rng/philox4x32_10.hpp:62:
In file included from /work/home/wangzh/rocRAND/library/src/rng/device_engines.hpp:32:
In file included from /work/home/wangzh/rocRAND/library/include/rocrand_kernel.h:29:
/work/home/wangzh/rocRAND/library/include/rocrand_philox4x32_10.h:199:47: error: no member named 'data' in 'uint4'
            unsigned int ret = m_state.result.data[m_state.substate];
                               ~~~~~~~~~~~~~~ ^
1 error generated.
make[2]: *** [library/CMakeFiles/rocrand.dir/build.make:63: library/CMakeFiles/rocrand.dir/src/rocrand.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:263: library/CMakeFiles/rocrand.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Thank you!

**Comment by ex-rzr** [comment]
You are using quite old versions of HCC and HIP. Is there any reason why you can't use the most recent versions?

**Comment by holyprince** [comment]
Yes, very sorry. I just a cluster user and the admin said that only the HCC1.5.0 and rocm 1.9 provided.

**Comment by ex-rzr** [comment]
In this case perhaps you can edit one file to manually revert this commit: https://github.com/ROCmSoftwarePlatform/rocRAND/commit/8a0ba3d7d8cb12067d32cedbe11153b7c1e70800

or pull a previous commit.

**Comment by holyprince** [comment]
Ok, I will try. Thank you very much.
