### ISSUE TITLE
rocRAND build with rocm 1.7?

### ISSUE THREAD

**Issue by QWU-AMD** [ROCmSoftwarePlatform/rocRAND#6]
Hi,

On the same machine, when rocm 1.6 is installed, rocRAND can be built. When rocm 1.7 is installed, the rocRAND build keeps failing. 

Are there any extra steps other than the instructions on the github page that I should take to build rocRAND with rocm 1.7?

Thanks,
Qiyu

**Comment by bragadeesh** [comment]
Can you please post the error message here

**Comment by QWU-AMD** [comment]
make -j4


Scanning dependencies of target sobol_direction_vector_generator
Scanning dependencies of target rocrand
Scanning dependencies of target mrg32k3a_precomputed_generator
Scanning dependencies of target xorwow_precomputed_generator
[  1%] Building CXX object tools/CMakeFiles/mrg32k3a_precomputed_generator.dir/mrg32k3a_precomputed_generator.cpp.o
[  3%] Building CXX object tools/CMakeFiles/sobol_direction_vector_generator.dir/sobol_direction_vector_generator.cpp.o
[  4%] Building CXX object tools/CMakeFiles/xorwow_precomputed_generator.dir/xorwow_precomputed_generator.cpp.o
[  6%] Building CXX object library/CMakeFiles/rocrand.dir/src/rocrand.cpp.o
[  8%] Linking CXX executable mrg32k3a_precomputed_generator
[  9%] Linking CXX executable xorwow_precomputed_generator
[  9%] Built target mrg32k3a_precomputed_generator
[ 11%] Linking CXX executable sobol_direction_vector_generator
[ 11%] Built target xorwow_precomputed_generator
[ 11%] Built target sobol_direction_vector_generator
[ 12%] Linking CXX shared library librocrand.so
[ 12%] Built target rocrand
Scanning dependencies of target test_rocrand_generate_normal
Scanning dependencies of target hiprand
Scanning dependencies of target test_rocrand_kernel_xorwow
Scanning dependencies of target test_rocrand_generate_log_normal
[ 14%] Building CXX object library/CMakeFiles/hiprand.dir/src/hiprand/hiprand_hcc.cpp.o
[ 16%] Building CXX object test/CMakeFiles/test_rocrand_generate_normal.dir/test_rocrand_generate_normal.cpp.o
[ 17%] Building CXX object test/CMakeFiles/test_rocrand_generate_log_normal.dir/test_rocrand_generate_log_normal.cpp.o
[ 19%] Building CXX object test/CMakeFiles/test_rocrand_kernel_xorwow.dir/test_rocrand_kernel_xorwow.cpp.o
[ 20%] Linking CXX shared library libhiprand.so
[ 22%] Linking CXX executable test_rocrand_generate_normal
[ 24%] Linking CXX executable test_rocrand_generate_log_normal
[ 24%] Built target hiprand
Scanning dependencies of target test_rocrand_philox_prng
[ 25%] Building CXX object test/CMakeFiles/test_rocrand_philox_prng.dir/test_rocrand_philox_prng.cpp.o
[ 25%] Built target test_rocrand_generate_normal
Scanning dependencies of target test_rocrand_kernel_philox4x32_10
[ 27%] Building CXX object test/CMakeFiles/test_rocrand_kernel_philox4x32_10.dir/test_rocrand_kernel_philox4x32_10.cpp.o
[ 27%] Built target test_rocrand_generate_log_normal
Scanning dependencies of target test_rocrand_mrg32k3a_prng
[ 29%] Building CXX object test/CMakeFiles/test_rocrand_mrg32k3a_prng.dir/test_rocrand_mrg32k3a_prng.cpp.o
[ 30%] Linking CXX executable test_rocrand_kernel_xorwow
/opt/rocm/hcc-1.0/bin/llc(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x1429afa]
/opt/rocm/hcc-1.0/bin/llc(_ZN4llvm3sys17RunSignalHandlersEv+0x3e)[0x1427bee]
/opt/rocm/hcc-1.0/bin/llc[0x1427d3c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f65b2bd0390]
[0x7fff3280a9a0]
Stack dump:
0.      Program arguments: /opt/rocm/hcc-1.0/bin/llc -O2 -mtriple amdgcn--amdhsa-amdgiz -mcpu=gfx803 -filetype=obj -enable-si-insert-waitcnts=0 -o /tmp/tmp.iTD5Lsn0JF/kernel-gfx803.hsaco.isabin /tmp/tmp.iTD5Lsn0JF/kernel-gfx803.hsaco.opt.bc
1.      Running pass 'Function Pass Manager' on module '/tmp/tmp.iTD5Lsn0JF/kernel-gfx803.hsaco.opt.bc'.
2.      Running pass 'Loop Pass Manager' on function '@_ZZN34rocrand_kernel_xorwow_rocrand_Test8TestBodyEvEN67HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_219__cxxamp_trampolineEPjm'
3.      Running pass 'Loop Strength Reduction' on basic block '%166'
/opt/rocm/hcc-1.0/bin/clamp-device: line 216: 16054 Segmentation fault      (core dumped) $LLC $KMOPTLLC -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -filetype=obj -enable-si-insert-waitcnts=0 -o $2.isabin $2.opt.bc
Generating AMD GCN kernel failed in llc for target: gfx803
/opt/rocm/hcc-1.0/bin/llc(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x1429afa]
/opt/rocm/hcc-1.0/bin/llc(_ZN4llvm3sys17RunSignalHandlersEv+0x3e)[0x1427bee]
/opt/rocm/hcc-1.0/bin/llc[0x1427d3c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f72a760c390]
[0x7ffe5abb8f00]
Stack dump:
0.      Program arguments: /opt/rocm/hcc-1.0/bin/llc -O2 -mtriple amdgcn--amdhsa-amdgiz -mcpu=gfx900 -filetype=obj -enable-si-insert-waitcnts=0 -o /tmp/tmp.iTD5Lsn0JF/kernel-gfx900.hsaco.isabin /tmp/tmp.iTD5Lsn0JF/kernel-gfx900.hsaco.opt.bc
1.      Running pass 'Function Pass Manager' on module '/tmp/tmp.iTD5Lsn0JF/kernel-gfx900.hsaco.opt.bc'.
2.      Running pass 'Loop Pass Manager' on function '@_ZZN34rocrand_kernel_xorwow_rocrand_Test8TestBodyEvEN67HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_219__cxxamp_trampolineEPjm'
3.      Running pass 'Loop Strength Reduction' on basic block '%166'
/opt/rocm/hcc-1.0/bin/clamp-device: line 216: 16056 Segmentation fault      (core dumped) $LLC $KMOPTLLC -mtriple amdgcn--amdhsa-amdgiz -mcpu=$AMDGPU_TARGET -filetype=obj -enable-si-insert-waitcnts=0 -o $2.isabin $2.opt.bc
Generating AMD GCN kernel failed in llc for target: gfx900
clang-6.0: error: linker command failed with exit code 161 (use -v to see invocation)
test/CMakeFiles/test_rocrand_kernel_xorwow.dir/build.make:103: recipe for target 'test/test_rocrand_kernel_xorwow' failed
make[2]: *** [test/test_rocrand_kernel_xorwow] Error 161
CMakeFiles/Makefile2:396: recipe for target 'test/CMakeFiles/test_rocrand_kernel_xorwow.dir/all' failed
make[1]: *** [test/CMakeFiles/test_rocrand_kernel_xorwow.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 32%] Linking CXX executable test_rocrand_kernel_philox4x32_10
[ 33%] Linking CXX executable test_rocrand_philox_prng
[ 33%] Built target test_rocrand_kernel_philox4x32_10
[ 33%] Built target test_rocrand_philox_prng
[ 35%] Linking CXX executable test_rocrand_mrg32k3a_prng
[ 35%] Built target test_rocrand_mrg32k3a_prng
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bragadeesh** [comment]
Thanks; how are you obtaining rocm 1.7? Why do you need to use an unreleased rocm version?
this is a known bug that has been fixed in our internal branch; the fix should soon propagate up
