### ISSUE TITLE
can not compile on Nvidia platform

### ISSUE THREAD

**Issue by eddy16112** [ROCmSoftwarePlatform/rocRAND#76]
I tried to compile to rocRAND on Nvidia platform, but I get the following error with make
```
 CMake Error at cmake/VerifyCompiler.cmake:34 (message):
   On ROCm platform 'hcc' or 'clang' must be used as C++ compiler.
 Call Stack (most recent call first):
   CMakeLists.txt:50 (include)
```
Should I always use clang? Can I use gnu?

**Comment by VincentSC** [comment]
There seems to be ROCm installed, or at least this is recognised, or Nvidia CUDA is not found. rocRAND makes use of [rocm-cmake](https://github.com/RadeonOpenCompute/rocm-cmake) - I think there you can get better answers why this happens on your machine.

**Comment by eddy16112** [comment]
Thanks for the suggestion. The machine has ROCm installed, but ROCm is not loaded into PATH/LD_LIBRARY_PATH, and CUDA is loaded, so I assume the rocRAND could figure it out. 

I fixed it by manually export HIP_PLATFORM=nvcc before cmake. Maybe you could add a flag in ccmake to let user switch between hip and nvcc.
