### ISSUE TITLE
Compilation issues form rocRand while building the mxnet

### ISSUE THREAD

**Issue by sriharikarnam** [ROCmSoftwarePlatform/rocRAND#81]
While building the hip port of mxnet with latest rocRAND, we observe compilation errors from rocRAND. Please find the log attached.
[mxnet_log_rocrand_issue.txt](https://github.com/ROCmSoftwarePlatform/rocRAND/files/3533292/mxnet_log_rocrand_issue.txt)
We needed some support regarding this issue.

ROCM version:
dpkg -s rocm-dkms
Package: rocm-dkms
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 13
Maintainer: Advanced Micro Devices Inc.
Architecture: amd64
Version: 2.7.22
Depends: rocm-dev, rock-dkms
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm

rocRAND Version:
dpkg -s rocrand 
Package: rocrand
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 25033
Maintainer: Saad Rahim <saad.rahim@amd.com>
Architecture: amd64
Version: 2.7.0.641-rocm-rel-2.7-22-dd953aa
Depends: hip_hcc (>= 1.5.19055)
Description: The rocRAND library provides functions that generate pseudo-random and quasi-random numbers.

**Comment by saadrahim** [comment]
There is an internal AMD ticket for this. Closing this here.
